### ISSUE TITLE
Album cover not shown and notifications don't work

### ISSUE THREAD

**Issue by dkadioglu** [Idea-Software/SpotifyControls#1]
With the most recent version 1.2.5 I don't see any Album covers. Instead there is the following error message in the console log:
`5908fecfeaffb57f8b846546ef08f7fc3dc1c112%22:1 GET chrome-extension://goikghbjckploljhlfmjjfggccmlnbea/%22https://d3rt1990lpmkn.cloudfront.net/unbranded/5908fecfeaffb57f8b846546ef08f7fc3dc1c112%22 net::ERR_FILE_NOT_FOUND`
This message appears again and again every second.
Another problem is that notifications are not shown and I cannot find any errors.
If you need further details, please ask.

**Comment by Sergej-Popov** [comment]
I will look into this today.. looks like something has changed on Spotify side which prevents generating image URL normally. It would be the same reason the notification is not working.

**Comment by Sergej-Popov** [comment]
Image URL parsing is now fixed. Fix is published as part of 1.2.6 package
